security:
  # Définition des hashers de mot de passe
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  # Définition du fournisseur d'utilisateurs
  providers:
    app_user_provider:
      entity:
        class: App\Entity\Users
        property: email # La propriété unique pour identifier l'utilisateur (email)

  # Définition des firewalls
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/ # Exclure ces chemins de l'authentification
      security: false # Désactiver la sécurité pour ces chemins

    main:
      lazy: true
      provider: app_user_provider
      form_login:
        login_path: login
        check_path: login
        username_parameter: email # Assure que le champ email est utilisé
        password_parameter: password # Symfony attend déjà "password"
      logout:
        path: logout
        target: /

  # Définition des contrôles d'accès
  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN } # Accès réservé aux administrateurs
    - { path: ^/profile, roles: ROLE_USER } # Accès réservé aux utilisateurs authentifiés
